### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'get_str'

### ISSUE THREAD

**Issue by chr7** [A-UNDERSCORE-D/edmc-screenshot-2#1]
Loading fails:
`  File "/home/ch/.local/share/EDMarketConnector/plugins/edmc-screenshot-2/load.py", line 152, in <module>  s = ScreenshotRenamer()
  File "/home/ch/.local/share/EDMarketConnector/plugins/edmc-screenshot-2/load.py", line 33, in __init__
    self.sshot_path = tk.StringVar(value=config.get_str(self.CONFIG_NAMES['sshot_path'], default=''))
AttributeError: 'Config' object has no attribute 'get_str'
`

EDMC 4.2.7
Python 3.8.5

**Comment by chr7** [comment]
I think that is due to a change in EDMC. In another plugin (exploration-progress), I found the following:

> def get_config_str_value(key):
    # Wrapper for either config.get_str() (EDMC <=5.0.0) or config.get (EDMC >5.0.0)
    if edmc_version > semantic_version.Version("5.0.0-beta1"):
        # At least EDMC 5.0.0
        logger.debug(f"EDMC version {edmc_version} should be at least 5.0.0-beta1")
        value = config.get_str(key)
    else:
        # Before EDMC 5.0.0
        logger.debug(f"EDMC version {edmc_version} should be before 5.0.0-beta1")
        value = config.get(key)
    return value

**Comment by A-UNDERSCORE-D** [comment]
Yeah that'll be due to you using an older version of EDMC. Sorry Im always running from source and thus dont always have a super good memory for what is and isnt in the released versions
