### ISSUE TITLE
Option to delete original file

### ISSUE THREAD

**Issue by BanditSan** [A-UNDERSCORE-D/edmc-screenshot-2#2]
One of reasons to use screenshot converter to reduce disk usage (unless you like fdev  way to waste disk space :D)
Would be nice to have such option like in original [EDMC-Screenshot](https://github.com/NoFoolLikeOne/EDMC-Screenshot)

**Comment by A-UNDERSCORE-D** [comment]
This option exists -- Not sure if you spotted it?

**Comment by BanditSan** [comment]
@A-UNDERSCORE-D 
Yes i did. Sorry for pointless issue :)
